# Generated by Django 5.0.2 on 2024-02-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('material', models.CharField(blank=True, default='Leather', max_length=100, null=True)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
