# Generated by Django 5.0.2 on 2024-02-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_trainer_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('trainer', models.ManyToManyField(related_name='trainer_images', to='trainers.trainer')),
            ],
        ),
    ]
