# Generated by Django 5.0.2 on 2024-02-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_trainerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='size',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrainerSizes',
        ),
    ]
