# Generated by Django 5.0.2 on 2024-02-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_trainer_size_delete_trainersizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerimage',
            name='trainer',
        ),
        migrations.AddField(
            model_name='trainer',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainer_images', to='trainers.trainerimage'),
        ),
    ]
