# Generated by Django 5.0.2 on 2024-03-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_alter_trainer_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerimage',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_images', to='trainers.trainer'),
            preserve_default=False,
        ),
    ]
