# Generated by Django 5.0.2 on 2024-03-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0010_remove_trainer_images_trainer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers_images', to='trainers.trainerimage'),
        ),
    ]
