# Generated by Django 5.0.2 on 2024-03-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0012_remove_trainer_image_remove_trainerimage_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='images',
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainers_images', to='trainers.trainerimage'),
        ),
        migrations.AddField(
            model_name='trainerimage',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trainers.trainer'),
            preserve_default=False,
        ),
    ]
