# Generated by Django 5.0.2 on 2024-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0014_alter_trainer_image_delete_trainerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
