# Generated by Django 5.0.2 on 2024-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0015_alter_trainer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='condition',
            field=models.CharField(default='brand new with tags', max_length=100),
            preserve_default=False,
        ),
    ]
