# Generated by Django 5.0.2 on 2024-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0016_trainer_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image_3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
