# Generated by Django 5.0.2 on 2024-03-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0017_trainer_image_2_trainer_image_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='image',
            new_name='image_1',
        ),
    ]
