# Generated by Django 5.0.2 on 2024-03-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0018_rename_image_trainer_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='condition',
            field=models.CharField(default='Good', max_length=100),
        ),
    ]
