# Generated by Django 5.0.2 on 2024-03-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0019_alter_trainer_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(default='male', max_length=50),
            preserve_default=False,
        ),
    ]
