# Generated by Django 5.0.3 on 2024-03-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0020_trainer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='available_stock',
            field=models.IntegerField(default=1),
        ),
    ]
