# Generated by Django 5.0.2 on 2024-03-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_basket_user'),
        ('trainers', '0008_alter_trainer_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='trainer',
        ),
        migrations.AddField(
            model_name='basket',
            name='trainer',
            field=models.ManyToManyField(to='trainers.trainer'),
        ),
    ]
