# Generated by Django 5.0.2 on 2024-03-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_basket_is_active_basket_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
    ]
