# Generated by Django 5.0.2 on 2024-03-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_remove_basket_total_price'),
        ('trainers', '0015_alter_trainer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='trainer',
            field=models.ManyToManyField(blank=True, null=True, to='trainers.trainer'),
        ),
    ]
