# Generated by Django 5.0.2 on 2024-03-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_alter_basket_trainer'),
        ('trainers', '0015_alter_trainer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='basket', to='trainers.trainer'),
        ),
    ]
